[package]
name = "oobforest"
version = "0.0.0"
edition = "2018"

[lib]
name = "oobforest"

[dependencies]
ndarray = "0.15.3"

[dev-dependencies]
rstest = "0.11.0"
assert_approx_eq = "1.1.0"
ndarray-rand = "0.14.0"
ndarray = { version = "0.15.3", features = ["approx"] }