[package]
name = "oobforest"
version = "0.0.0"
edition = "2018"

[lib]
name = "oobforest"

[dependencies]
ndarray = "0.15.3"
rand = "0.8.4"

[dev-dependencies]
rstest = "0.11.0"
assert_approx_eq = "1.1.0"
ndarray-rand = "0.14.0"
ndarray = { version = "0.15.3", features = ["approx"] }
csv = "^1"
ndarray-csv = "^0.5"
criterion = "0.3.0"

[[bench]]
name = "bench_forest"
harness = false